config/routes.rb
Rails.application.routes.draw do
  get 'reports/general'

  resources :courses
  resources :hackers do
		put :activate, on: :member
	end
  resources :generations
  resources :languages

  root to: "generations#index"

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :generation
end

app/models/generation.rb
class Generation < ActiveRecord::Base
  has_many :hackers
  has_many :courses
end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  belongs_to :generation
  has_and_belongs_to_many :languages

  before_destroy :verify_if_theres_at_least_one


	def active?
		status == 'active'
	end

  private

  def verify_if_theres_at_least_one
    if Hacker.count == 1
      false
    else
      true
    end
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_and_belongs_to_many :hackers


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :dificulty, :generation_id)
    end
end

app/controllers/generations_controller.rb
class GenerationsController < ApplicationController

  def index
    @generations = Generation.all
  end

  def new
    @generation = Generation.new
  end

  def create
    @generation = Generation.new generation_params
    if @generation.save
      flash[:notice] = "Generación fue creada exitosamente"
      redirect_to generations_path
    else
      render :new
    end
  end

  def edit
    @generation = Generation.find(params[:id])
  end

  def update
    @generation = Generation.find(params[:id])
    if @generation.update_attributes(generation_params)
      flash[:notice] = "Generación actualizada exitosamente"
      redirect_to generations_path
    else
      render :edit
    end
  end

  def destroy
    @generation = Generation.find(params[:id])
    @generation.destroy
    flash[:notice] = "Generación eliminada exitosamente"
    redirect_to generations_path
  end

  private

  def generation_params
    params.require(:generation).permit(:name, :start_date)
  end
end

app/controllers/hackers_controller.rb
class HackersController < ApplicationController
  before_action :set_hacker, only: [:show, :edit, :update, :destroy, :activate]

  # GET /hackers
  # GET /hackers.json
  def index
    @hackers = Hacker.all
  end

  # GET /hackers/1
  # GET /hackers/1.json
  def show
  end

  # GET /hackers/new
  def new
    @hacker = Hacker.new
  end

  # GET /hackers/1/edit
  def edit
  end

  # POST /hackers
  # POST /hackers.json
  def create
    @hacker = Hacker.new(hacker_params)

    respond_to do |format|
      if @hacker.save
        format.html { redirect_to hackers_path, notice: 'Hacker was successfully created.' }
        format.json { render :show, status: :created, location: @hacker }
      else
        format.html { render :new }
        format.json { render json: @hacker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hackers/1
  # PATCH/PUT /hackers/1.json
  def update
    respond_to do |format|

      if @hacker.update(hacker_params)
        format.html { redirect_to @hacker, notice: 'Hacker was successfully updated.' }
        format.json { render :show, status: :ok, location: @hacker }
      else
        format.html { render :edit }
        format.json { render json: @hacker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hackers/1
  # DELETE /hackers/1.json
  def destroy
    @hacker.destroy
    respond_to do |format|
      format.html { redirect_to hackers_url, notice: 'Hacker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate
		@hacker.status = @hacker.active? ? 'inactive' : 'active'
		@hacker.save
		redirect_to hackers_path, notice: "#{@hacker.name}'s status was changed to #{@hacker.status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hacker
      @hacker = Hacker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hacker_params
      params.require(:hacker).permit(:name, :email, :generation_id, language_ids: [])
    end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:name, :skill, :hacker_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def general
    @generation = Generation.last
    @hackers = Hacker.where(generation_id: @generation.id)
    @courses = Course.where(generation_id: @generation.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/generations_helper.rb
module GenerationsHelper
end

app/helpers/hackers_helper.rb
module HackersHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dificulty %><br>
    <%= f.text_field :dificulty %>
  </div>
  <div class="field">
    <%= f.label :generation_id %><br>
    <%= f.select :generation_id, Generation.all.map {|generation| [generation.name, generation.id]}, include_blank: "Seleccione" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Dificulty</th>
      <th>Generation</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.name, course %></td>
        <td><%= course.dificulty %></td>
        <td><%= course.generation.name %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Dificulty:</strong>
  <%= @course.dificulty %>
</p>

<p>
  <strong>Generation:</strong>
  <%= @course.generation.name %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/generations/_form.html.erb
<%= form_for @generation, :html => { :class => "form-horizontal generation" } do |f| %>

  <% if @generation.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@generation.errors.count, "error") %> prohibited this generation from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @generation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <label class="control-label col-lg-2">Nombre</label>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <label class="control-label col-lg-2">Fecha de Inicio</label>
    <div class="col-lg-10">
      <%= f.text_field :start_date, :class => 'form-control datepicker' %>
    </div>
    <%=f.error_span(:start_date) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Guardar", :class => 'btn btn-primary' %>
      <%= link_to "Cancelar",
                generations_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/generations/edit.html.erb
<%- model_class = Generation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/generations/index.html.erb
<div class="page-header">
  <h1>Generaciones</h1>
</div>

<div class="pull-right">
<%= link_to "Nueva Generación",
            new_generation_path,
            :class => 'btn btn-primary' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Fecha de Inicio</th>
      <th>Creado en </th>
      <th>Actualizado en</th>
    </tr>
  </thead>
  <tbody>
    <% @generations.each do |generation| %>
      <tr>
        <td><%= link_to generation.id, generation_path(generation) %></td>
        <td><%= generation.name %></td>
        <td><%= generation.start_date.strftime("%d/%B/%Y") %></td>
        <td><%= generation.created_at.strftime("%d/%B/%Y %H:%M") %></td>
        <td><%= generation.updated_at.strftime("%d/%B/%Y %H:%M") %></td>
        <td>
          <%= link_to "Editar",
                      edit_generation_path(generation), class: 'btn btn-default btn-xs' %>
          <%= link_to "Eliminar",
                      generation_path(generation),
                      :method => :delete,
                      :data => { confirm: "¿Estás seguro?" },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/generations/new.html.erb
<div class="page-header">
  <h1>Nueva Generación</h1>
</div>
<%= render 'form' %>

app/views/generations/show.html.erb
<%- model_class = Generation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @generation.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @generation.start_date %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              generations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_generation_path(@generation), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              generation_path(@generation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/hackers/_form.html.erb
<%= form_for(@hacker) do |f| %>
  <% if @hacker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hacker.errors.count, "error") %> prohibited this hacker from being saved:</h2>

      <ul>
      <% @hacker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="control-label col-lg-2">Nombre</label>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <label class="control-label col-lg-2">Email</label>
    <%= f.text_field :email %>
  </div>


  <div class="form-group">
    <label class="control-label col-lg-2">Generación</label>
    <%= f.select :generation_id, Generation.all.map {|generation| [generation.name, generation.id]}, include_blank: "Seleccione" %>
	</div>

	<div>
		<label class="control-label col-lg-2">Lenguajes</label>
		<%= f.collection_select :language_ids, Language.order(:name), :id, :name, {}, {multiple: true}
 %>	</div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Guardar", :class => 'btn btn-primary' %>
      <%= link_to "Cancelar",
                hackers_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/hackers/edit.html.erb
<h1>Editing Hacker</h1>

<%= render 'form' %>

<%= link_to 'Show', @hacker %> |
<%= link_to 'Back', hackers_path %>

app/views/hackers/index.html.erb
<div class="page-header">
  <h1>Hackers</h1>
</div>

<div class="pull-right">
<%= link_to "Nuevo Hacker",
            new_hacker_path,
            :class => 'btn btn-primary' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
			<th>Generation</th>
			<th>Status</th>
      <th>Languages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hackers.each do |hacker| %>
      <tr>
        <td><%= link_to hacker.name, hacker %></td>
        <td><%= hacker.email %></td>
				<td><%= hacker.generation.name %></td>
				<td><%= hacker.status.upcase %></td>
        <td><%= hacker.languages.map(&:name).join(", ") %></td>
        <td>

        <%= link_to "Editar",
                      edit_hacker_path(hacker), class: 'btn btn-default btn-xs' %>
          <%= link_to "Eliminar",
                      hacker_path(hacker),
                      :method => :delete,
                      :data => { confirm: "¿Estás seguro?" },
											:class => 'btn btn-xs btn-danger' %>
							<%= link_to "#{ hacker.active? ? 'Deactivate' : 'Activate'}",
											activate_hacker_path(hacker),
											method: :put,
											class: 'btn btn-xs btn-info'	%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/hackers/languages.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @hacker.name %>'s language<%= @hacker.languages.size > 1 ? "s" : "" %></h1>

<ul>
  <% @hacker.languages.each do |lang| %>
  <li><%= lang.name %> | <b>Skill:</b> <%= lang.skill %></li>
  <% end %>
</ul>

app/views/hackers/new.html.erb
<h1>Nuevo Hacker</h1>

<%= render 'form' %>

<%= link_to 'Back', hackers_path %>

app/views/hackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @hacker.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @hacker.email %>
</p>

<p>
  <strong>Generación:</strong>
  <%= @hacker.generation.name %>
</p>

<p>
  <strong>Lenguajes</strong>
  <ul>
    <% @hacker.languages.each do |lang|  %>
    <li><%= lang.name %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_hacker_path(@hacker) %> |
<%= link_to 'Back', hackers_path %>

app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
  <% if @language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% @language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing Language</h1>

<%= render 'form' %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Languages</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.name %></td>
        <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Edit', edit_language_path(language) %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<h1>New Language</h1>

<%= render 'form' %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>



<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HackerschoolDirectory" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">HackerschoolDirectory</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Generaciones", generations_path  %></li>
            <li><%= link_to "Hackers", hackers_path  %></li>
            <li><%= link_to "Cursos", courses_path  %></li>
            <li><%= link_to "Lenguajes", languages_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Hackerschool 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/reports/general.html.erb
<h1>
  Reporte
</h1>

<h2>Hacker section - (<%= @hackers.length %>)</h2>
<ul>
  <% @hackers.each do |hacker| %>
  <li><%= hacker.name %></li>
  <% end %>

</ul>





<h2>Course section - (<%= @courses.size %>)</h2>
<ul>
  <% @courses.each do |course| %>
  <li><%= course.name %></li>
  <% end %>
</ul>